application: amfiquery
version: 1
runtime: python
api_version: 1

default_expiration: 7d  # This is good for images, which never change

handlers:

- url: /(robots.txt|favicon.ico|index.html|style.css)
  static_files: static/\1
  upload: static/(robots.txt|favicon.ico|index.html|style.css)

- url: /static
  static_dir: static

- url: .*
  script: main.py
